/*
 * This file is autogenerated by the attrib.c program, do not edit 
 */

namespace Unix.Terminal {
	partial class Curses {
		public const int A_NORMAL = 0x0;
		public const int A_STANDOUT = 0x10000;
		public const int A_UNDERLINE = 0x20000;
		public const int A_REVERSE = 0x40000;
		public const int A_BLINK = 0x80000;
		public const int A_DIM = 0x100000;
		public const int A_BOLD = 0x200000;
		public const int A_PROTECT = 0x1000000;
		public const int A_INVIS = 0x800000;
		public const int ACS_LLCORNER = 0x40006d;
		public const int ACS_LRCORNER = 0x40006a;
		public const int ACS_HLINE = 0x400071;
		public const int ACS_ULCORNER = 0x40006c;
		public const int ACS_URCORNER = 0x40006b;
		public const int ACS_VLINE = 0x400078;
		public const int ACS_LTEE = 0x400074;
		public const int ACS_RTEE = 0x400075;
		public const int ACS_BTEE = 0x400076;
		public const int ACS_TTEE = 0x400077;
		public const int ACS_PLUS = 0x40006e;
		public const int ACS_S1 = 0x40006f;
		public const int ACS_S9 = 0x400073;
		public const int ACS_DIAMOND = 0x400060;
		public const int ACS_CKBOARD = 0x400061;
		public const int ACS_DEGREE = 0x400066;
		public const int ACS_PLMINUS = 0x400067;
		public const int ACS_BULLET = 0x40007e;
		public const int ACS_LARROW = 0x40002c;
		public const int ACS_RARROW = 0x40002b;
		public const int ACS_DARROW = 0x40002e;
		public const int ACS_UARROW = 0x40002d;
		public const int ACS_BOARD = 0x400068;
		public const int ACS_LANTERN = 0x400069;
		public const int ACS_BLOCK = 0x400030;
		public const int COLOR_BLACK = 0x0;
		public const int COLOR_RED = 0x1;
		public const int COLOR_GREEN = 0x2;
		public const int COLOR_YELLOW = 0x3;
		public const int COLOR_BLUE = 0x4;
		public const int COLOR_MAGENTA = 0x5;
		public const int COLOR_CYAN = 0x6;
		public const int COLOR_WHITE = 0x7;
		public const int KEY_CODE_YES = 0x100;
		public const int ERR = unchecked((int) 0xffffffff);
		public const int KeyBackspace = 0x107;
		public const int KeyUp = 0x103;
		public const int KeyDown = 0x102;
		public const int KeyLeft = 0x104;
		public const int KeyRight = 0x105;
		public const int KeyNPage = 0x152;
		public const int KeyPPage = 0x153;
		public const int KeyHome = 0x106;
		public const int KeyMouse = 0x199;
		public const int KeyEnd = 0x168;
		public const int KeyDeleteChar = 0x14a;
		public const int KeyInsertChar = 0x14b;
		public const int KeyBackTab = 0x161;
		public const int KeyF1 = 0x109;
		public const int KeyF2 = 0x10a;
		public const int KeyF3 = 0x10b;
		public const int KeyF4 = 0x10c;
		public const int KeyF5 = 0x10d;
		public const int KeyF6 = 0x10e;
		public const int KeyF7 = 0x10f;
		public const int KeyF8 = 0x110;
		public const int KeyF9 = 0x111;
		public const int KeyF10 = 0x112;
		public const int KeyResize = 0x19a;


		public static int ColorPair(int n)
		{
			return 0 + n * 256;
		}

		internal enum Event : long {
			Button1Pressed = 0x2,
			Button1Released = 0x1,
			Button1Clicked = 0x4,
			Button1DoubleClicked = 0x8,
			Button1TripleClicked = 0x10,
			Button2Pressed = 0x80,
			Button2Released = 0x40,
			Button2Clicked = 0x100,
			Button2DoubleClicked = 0x200,
			Button2TrippleClicked = 0x400,
			Button3Pressed = 0x2000,
			Button3Released = 0x1000,
			Button3Clicked = 0x4000,
			Button3DoubleClicked = 0x8000,
			Button3TripleClicked = 0x10000,
			Button4Pressed = 0x80000,
			Button4Released = 0x40000,
			Button4Clicked = 0x100000,
			Button4DoubleClicked = 0x200000,
			Button4TripleClicked = 0x400000,
			ButtonShift = 0x2000000,
			ButtonCtrl = 0x1000000,
			ButtonAlt = 0x4000000,
			ReportMousePosition = 0x8000000,
			AllEvents = 0x7ffffff
		}
	}
}